server:
  port: 2022
  
spring:
  datasource:
    url: jdbc:mysql://localhost/spring
    username: root
    password: 4562
    driver-class-name: com.mysql.cj.jdbc.Driver 
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: Vaccine-SERVICE 
    